ad.security.permission_profiles._default.permissions.sas=1
ad.wol.mac_hash=795bee3197918189036b07f63df7eea700d62edd
ad.anynet.client_stats_hash=f1532100ca8429e91b0b2d9945cc2200bf323f92
ad.anynet.fpr=5101c0e13eeeb1b058719d021df16b14fc4f5d98
ad.security.update_version=1
ad.inst.id=a74f28bd2e256dae9c1f2e4fdc78efd2
ad.anynet.network_id=main
ad.anynet.relay.fatal_result=1.0
ad.anynet.id=
ad.license.name=free-1
ad.security.frontend_clipboard_version=1
ad.anynet.did.hash=0
ad.ancl.cached_config.v1=
ad.anynet.last_relay=relay-d3cb6642.net.anydesk.com:80:443:6568
ad.license.expiry=0
ad.anynet.relay.state=2
ad.security.frontend_clipboard=1
ad.anynet.alias=
ad.security.frontend_clipboard_files=1
ad.security.permission_profiles._unattended_access.permissions.sas=1
ad.security.permission_profiles.version=1
ad.anynet.cur_version=38655098888
